// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChronoController from "./chrono_controller.js"
application.register("chrono", ChronoController)

import ChronoNewSummaryController from "./chrono_new_summary_controller.js"
application.register("chrono-new-summary", ChronoNewSummaryController)

import LookupController from "./lookup_controller.js"
application.register("lookup", LookupController)

import PopoverController from "./popover_controller.js"
application.register("popover", PopoverController)

import RemotePartialController from "./remote_partial_controller.js"
application.register("remote-partial", RemotePartialController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import SwitchController from "./switch_controller.js"
application.register("switch", SwitchController)

import UnsavedChangesController from "./unsaved_changes_controller.js"
application.register("unsaved-changes", UnsavedChangesController)

import UserNameController from "./user_name_controller.js"
application.register("user-name", UserNameController)

import WizardFormController from "./wizard_form_controller.js"
application.register("wizard-form", WizardFormController)
