exclude:
  - '*.yml'

linters:
  LineLength:
    max: 120
    exclude:
      - 'app/views/devise/registrations/edit.html.haml'
      - 'app/views/chrono/new.html.haml'

  IdNames:
    exclude:
      - 'app/views/devise/shared/_error_messages.html.haml'

  ViewLength:
    exclude:
      - 'app/views/goggles/_inline_mailer_styles.html.haml'
      - 'app/views/chrono/new.html.haml'

  RuboCop:
    exclude:
      - 'app/components/combo_box/db_lookup_component.html.haml'
      - 'app/views/application_mailer/generic_message.html.haml'
      - 'app/views/datagrid/_form.html.haml'
      - 'app/views/datagrid/_order_for.html.haml'
      - 'app/views/datagrid/_table.html.haml'
      - 'app/views/devise/registrations/edit.html.haml'
      - 'app/views/home/_contributing.html.haml'
      - 'app/views/home/_faq.html.haml'
      - 'app/views/home/_how_does_it_work.html.haml'
      - 'app/views/home/_legal_terms.html.haml'
      - 'app/views/home/_privacy_policy.html.haml'
      - 'app/views/home/about.html.haml'
      - 'app/views/kaminari/_gap.html.haml'
      - 'app/views/teams/_swimmer_list.html.haml'
