exclude:
  - '*.yml'

linters:
  LineLength:
    max: 120
    exclude:
      - 'app/views/devise/registrations/edit.html.haml'

  IdNames:
    exclude:
      - 'app/views/devise/shared/_error_messages.html.haml'

  ViewLength:
    exclude:
      - 'app/views/goggles/_inline_mailer_styles.html.haml'
