require:
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.4
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

FactoryBot/SyntaxMethods:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 165
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/decorators/swimming_pool_decorator.rb'

Metrics/BlockLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'db/schema.rb'
    - 'lib/capistrano/tasks/db.rake'
    - 'lib/capistrano/tasks/status.rake'
    - 'lib/tasks/stats.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
  - 'app/controllers/chrono_controller.rb'
  - 'app/controllers/meetings_controller.rb'
  - 'app/controllers/swimmers_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'


# We use arrays to group multiple similar specs under a single implementation
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'spec/**/*'


Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20210513155157_change_user_results.rb'
    - 'db/migrate/20210513170020_add_seq_to_import_queues.rb'
    - 'db/migrate/20210514131355_rename_associations_in_user_results.rb'
    - 'db/migrate/20210611120440_add_support_fields_to_import_queues.rb'

# Excluded files here were already corrected in later migrations:
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/migrate/20210513113601_create_goggles_db_user_workshops.rb'
    - 'db/migrate/20220228114607_add_cancelled_to_calendars.rb'
    - 'db/migrate/20220801110842_add_sql_batch_field_to_import_queues.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'
    - 'db/migrate/20230530165750_clear_non_existing_associated_user_id.rb'
    - 'db/migrate/20210630154722_data_fix_badges_with_null_entry_time_type.rb'
    - 'db/migrate/20240204165000_data_fix_remove_null_rank_values.rb'

Rake/Desc:
  Exclude:
    - 'lib/tasks/cucumber.rake'

Rake/DuplicateTask:
  Exclude:
    - 'lib/tasks/cucumber.rake'

Rake/MethodDefinitionInTask:
  Exclude:
    - 'lib/capistrano/tasks/db.rake'
    - 'lib/tasks/stats.rake'


RSpec/IndexedLet:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/support/shared_component_examples.rb'

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: true
  Exclude:
    - 'spec/views/chrono/index.html.haml_spec.rb'
    - 'spec/views/tools/fin_score.html.haml_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10
  Exclude:
    - 'spec/decorators/iq_request/chrono_rec_param_adapter_spec.rb'
    - 'spec/requests/tools_controller_spec.rb'


Style/ClassAndModuleChildren:
  Exclude:
  - 'api/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Style/FormatStringToken:
  Exclude:
    - 'lib/capistrano/tasks/*'
