require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 165
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/decorators/swimming_pool_decorator.rb'

Metrics/BlockLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'lib/capistrano/tasks/db.rake'
    - 'lib/capistrano/tasks/status.rake'
    - 'lib/tasks/stats.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
  - 'app/controllers/chrono_controller.rb'
  - 'app/controllers/swimmers_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'


# We use arrays to group multiple similar specs under a single implementation
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'spec/**/*'


Rake/Desc:
  Exclude:
    - 'lib/tasks/cucumber.rake'

Rake/DuplicateTask:
  Exclude:
    - 'lib/tasks/cucumber.rake'

Rake/MethodDefinitionInTask:
  Exclude:
    - 'lib/capistrano/tasks/db.rake'
    - 'lib/tasks/stats.rake'


RSpec/Capybara/CurrentPathExpectation:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: true
  Exclude:
    - 'spec/views/chrono/index.html.haml_spec.rb'
    - 'spec/views/tools/fin_score.html.haml_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10
  Exclude:
    - 'spec/decorators/iq_request/chrono_rec_param_adapter_spec.rb'
    - 'spec/requests/tools_controller_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
  - 'api/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Style/FormatStringToken:
  Exclude:
    - 'lib/capistrano/tasks/*'
