# --- Common stuff:
FROM ruby:3.4.7-alpine3.22 AS common_builder
ENV BUNDLER_VERSION=2.4.15 \
    INSTALL_PATH=/app

RUN mkdir -p $INSTALL_PATH
RUN apk add --update --no-cache \
    binutils-gold \
    build-base \
    curl \
    file \
    g++ \
    gcc \
    git \
    less \
    libstdc++ \
    libffi-dev \
    libc-dev \
    linux-headers \
    libxml2-dev \
    libxslt-dev \
    libgcrypt-dev \
    make \
    mariadb-client \
    mariadb-dev \
    netcat-openbsd \
    openssl \
    pkgconfig \
    shadow \
    shared-mime-info \
    ssmtp \
    yaml-dev \
    tzdata

# Run as a specific user:
# ARG USER_ID
# ARG GROUP_ID
# RUN addgroup -g $GROUP_ID -S dev
# RUN adduser -D -g '' -u $USER_ID -G dev dev
# RUN chown -R dev:dev $INSTALL_PATH
# USER $USER_ID

# Rename the default container user which will result as sending out all e-mails:
RUN usermod -c 'Goggles Dev Mailer' root

# App image:
RUN gem install bundler -v $BUNDLER_VERSION

# --- Image-specific stuff:
FROM common_builder
ENV RAILS_ENV=development \
    DATABASE_NAME=goggles_development \
    DATABASE_HOST=goggles-db \
    DATABASE_PORT=3306 \
    DATABASE_USER=root

# Current export defaults:
# BUNDLE_APP_CONFIG='/usr/local/bundle'
# BUNDLE_PATH='/usr/local/bundle'
# GEM_HOME='/usr/local/bundle'

WORKDIR $INSTALL_PATH
COPY . ./
RUN bundle config build.nokogiri --use-system-libraries
COPY ./config/database.docker.yml ./config/database.yml


# As in goggles_api:
# RUN bundle install --jobs 4 --retry 3 || \
#     bundle install --jobs 4 --retry 5 --full-index
# Original:
RUN bundle check || bundle install

RUN bundle exec rails dartsass:build

# Keep the version argument at the end to avoid early cache miss during builds:
ARG TAG
ENV TAG=${TAG:-latest}
RUN echo "Version: $TAG"
LABEL AUTHOR=steve.alloro@gmail.com VERSION=$TAG

ENTRYPOINT ["./entrypoints/docker.dev.sh"]
