version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

common-config: &common-config
  working_directory: ~/goggles_main
  shell: /bin/bash --login
  # NOTE: make sure ENV vars on CircleCI include CC_TEST_REPORTER_ID
  #       for CodeClimate test coverage upload!
  #       (Otherwise the 'upload-coverage' step will fail.)
  docker:
    - image: cimg/ruby:3.1.4-node
      environment:
        RAILS_ENV: test
        BUNDLE_JOBS: 2
        BUNDLE_RETRY: 2
        BUNDLE_PATH: vendor/bundle
        PAGER: cat
        GIT_LFS_SKIP_SMUDGE: 1
    - image: cimg/mariadb:10.6.12
      environment:
        DATABASE_NAME: goggles_test
        DATABASE_USER: root
        PAGER: cat

common-db-setup: &common-db-setup
  name: DB setup
  command: |
    sudo apt update
    sudo apt-get install mysql-client
    mkdir -p tmp ~/test-results ~/test-artifacts
    echo $RAILS_MASTER_KEY > config/master.key
    cp ./tmp/test.sql.bz2 db/dump/test.sql.bz2
    mv config/database_ci.yml config/database.yml
    dockerize -wait tcp://localhost:3306 -timeout 1m
    RAILS_ENV=test bin/rails db:rebuild from=test to=test
    RAILS_ENV=test bin/rails db:migrate
    ./tmp/cc-test-reporter before-build

jobs:
  persisted-data:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - run:
          name:  Setup persisted data
          command: |
            mkdir -p tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            curl -L -o ./tmp/test.sql.bz2 "https://github.com/steveoro/goggles_db/raw/master/spec/dummy/db/dump/test.sql.bz2"
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
            - test.sql.bz2

  rubocop:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - ruby/rubocop-check:
          app-dir: ~/goggles_main
          label: Rubocop
          format: pacman

  brakeman:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          name: Brakeman
          command: |
            bundle exec brakeman -A6q -c .brakeman.cfg

  zeitwerk:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Zeitwerk check
          command: |
            bundle exec rake zeitwerk:check


  rspec-A-F:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - A..F
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/a*_spec.rb,spec/**/b*_spec.rb,spec/**/c*_spec.rb,spec/**/f*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-a-f.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-a-f.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-a-f.*.json


  rspec-I-L:
    <<: *common-config
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - I..L
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/i*_spec.rb,spec/**/l*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-i-l.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-i-l.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-i-l.*.json


  rspec-M:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - M
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/m*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-m.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-m.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-m.*.json


  rspec-S-T:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - S..T
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/s*_spec.rb,spec/**/t*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-s-t.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-s-t.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-s-t.*.json


  rspec-U:
    <<: *common-config
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - U
          command: |
            TEST_FILES=$(circleci tests glob "spec/**/u*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-u.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-u.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-u.*.json


  upload-coverage:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - attach_workspace:
          at: ~/goggles_main/tmp
      - run:
          name: CodeClimate upload
          command: |
            echo "*** Persisted contents: ***"
            ls -l ./tmp
            ./tmp/cc-test-reporter sum-coverage -o - tmp/codeclimate.*.json | ./tmp/cc-test-reporter upload-coverage --debug --input -


  docker-build:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Docker TAGGED prod
                command: |
                  echo "Git Tag << pipeline.git.tag >>"
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                  docker pull $DOCKERHUB_USERNAME/goggles-main:latest
                  docker build -t $DOCKERHUB_USERNAME/goggles-main:prod-<< pipeline.git.tag >> --cache-from=$DOCKERHUB_USERNAME/goggles-main:latest -f Dockerfile.prod .
                  docker push $DOCKERHUB_USERNAME/goggles-main:prod-<< pipeline.git.tag >>
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Docker LATEST staging
                command: |
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                  docker pull $DOCKERHUB_USERNAME/goggles-main:latest
                  docker build -t $DOCKERHUB_USERNAME/goggles-main:latest --cache-from=$DOCKERHUB_USERNAME/goggles-main:latest -f Dockerfile.staging .
                  docker push $DOCKERHUB_USERNAME/goggles-main:latest


workflows:
  full-build:
    jobs:
      - persisted-data
      - brakeman:
          requires:
            - persisted-data
      - rubocop:
          requires:
            - persisted-data
      - zeitwerk:
          requires:
            - persisted-data

      - rspec-A-F:
          requires:
            - brakeman
            - rubocop
            - zeitwerk

      - rspec-I-L:
          requires:
            - brakeman
            - rubocop
            - zeitwerk

      - rspec-M:
          requires:
            - rspec-A-F
      - rspec-S-T:
          requires:
            - rspec-I-L
      - rspec-U:
          requires:
            - rspec-A-F

      - upload-coverage:
          requires:
            - rspec-M
            - rspec-S-T
            - rspec-U

      - docker-build:
          requires:
            - upload-coverage
