version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

common-config: &common-config
  working_directory: ~/goggles_main
  shell: /bin/bash --login
  # NOTE: make sure ENV vars on CircleCI include CC_TEST_REPORTER_ID
  #       for CodeClimate test coverage upload!
  #       (Otherwise the 'upload-coverage' step will fail.)
  docker:
    - image: cimg/ruby:3.1.4-node
      environment:
        RAILS_ENV: test
        BUNDLE_JOBS: 2
        BUNDLE_RETRY: 2
        BUNDLE_PATH: vendor/bundle
        PAGER: cat
        GIT_LFS_SKIP_SMUDGE: 1
    - image: cimg/mariadb:10.6.12
      environment:
        DATABASE_NAME: goggles_test
        DATABASE_USER: root
        PAGER: cat

common-db-setup: &common-db-setup
  name: DB setup
  command: |
    sudo apt update
    sudo apt-get install mysql-client
    mkdir -p tmp ~/test-results ~/test-artifacts
    echo $RAILS_MASTER_KEY > config/master.key
    cp ./tmp/test.sql.bz2 db/dump/test.sql.bz2
    mv config/database_ci.yml config/database.yml
    yarn
    dockerize -wait tcp://localhost:3306 -timeout 1m
    RAILS_ENV=test bin/rails db:rebuild from=test to=test
    RAILS_ENV=test bin/rails db:migrate
    RAILS_ENV=test bundle exec bin/webpack
    ./tmp/cc-test-reporter before-build

jobs:
  persisted-data:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - run:
          name:  Setup persisted data
          command: |
            mkdir -p tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            curl -L -o ./tmp/test.sql.bz2 "https://github.com/steveoro/goggles_db/raw/master/spec/dummy/db/dump/test.sql.bz2"
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
            - test.sql.bz2

  rubocop:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - ruby/rubocop-check:
          app-dir: ~/goggles_main
          label: Rubocop
          format: pacman

  brakeman:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          name: Brakeman
          command: |
            bundle exec brakeman -A6q -c .brakeman.cfg

  zeitwerk:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Zeitwerk check
          command: |
            bundle exec rake zeitwerk:check


  rspec-components:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/components/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-components.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-components.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-components.*.json


  rspec-decorators:
    <<: *common-config
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/decorators/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-decorators.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-decorators.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-decorators.*.json


  rspec-helpers:
    <<: *common-config
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/helpers/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-helpers.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-helpers.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-helpers.*.json


  rspec-jobs:
    <<: *common-config
    # parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-jobs.xml \
                        -f doc -P spec/jobs/**/*_spec.rb
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-jobs.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-jobs.*.json


  rspec-mailers:
    <<: *common-config
    # parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-mailers.xml \
                        -f doc -P spec/mailers/**/*_spec.rb
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-mailers.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-mailers.*.json


  rspec-requests:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/requests/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-requests.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-requests.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-requests.*.json


  rspec-strategies:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/strategies/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-strategies.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-strategies.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-strategies.*.json


  rspec-views:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            TEST_FILES=$(circleci tests glob "spec/views/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-views.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-views.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-views.*.json


  rspec-integration:
    <<: *common-config
    # parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - Components
          command: |
            bundle exec rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out ~/test-results/rspec-integration.xml \
                        -f doc -P spec/integration/**/*_spec.rb
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "./tmp/codeclimate.rspec-integration.$CIRCLE_NODE_INDEX.json"
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.rspec-integration.*.json


  upload-coverage:
    <<: *common-config
    # parallelism: 1 (no actual need here)
    steps:
      - attach_workspace:
          at: ~/goggles_main/tmp
      - run:
          name: CodeClimate upload
          command: |
            echo "*** Persisted contents: ***"
            ls -l ./tmp
            ./tmp/cc-test-reporter sum-coverage -o - tmp/codeclimate.*.json | ./tmp/cc-test-reporter upload-coverage --debug --input -


  cucumber-desktop:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Cucumber - desktop
          command: |
            TEST_FILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
            AUTO_ARTIFACTS=1 RAILS_ENV=test bundle exec cucumber --color --format pretty \
                        --format junit --out ~/test-results/cucumber-large.xml ${TEST_FILES}
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts


  cucumber-narrow:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Cucumber - mobile/narrow
          command: |
            TEST_FILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
            CAPYBARA_DRV=headless_chrome_iphonex AUTO_ARTIFACTS=1 RAILS_ENV=test bundle exec cucumber --color --format pretty \
                        --format junit --out ~/test-results/cucumber-narrow.xml ${TEST_FILES}
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts


  cucumber-tablet:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_main/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Cucumber - mobile/tablet
          command: |
            TEST_FILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
            CAPYBARA_DRV=headless_chrome_ipad AUTO_ARTIFACTS=1 RAILS_ENV=test bundle exec cucumber --color --format pretty \
                        --format junit --out ~/test-results/cucumber-tablet.xml ${TEST_FILES}
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-artifacts


  docker-build:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_main
          key: goggles_main-v0600
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Docker TAGGED prod
                command: |
                  echo "Git Tag << pipeline.git.tag >>"
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                  docker pull $DOCKERHUB_USERNAME/goggles-main:latest
                  RAILS_ENV=production bundle exec rails assets:precompile
                  docker build -t $DOCKERHUB_USERNAME/goggles-main:prod-<< pipeline.git.tag >> --cache-from=$DOCKERHUB_USERNAME/goggles-main:latest -f Dockerfile.prod .
                  docker push $DOCKERHUB_USERNAME/goggles-main:prod-<< pipeline.git.tag >>
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Docker LATEST staging
                command: |
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                  docker pull $DOCKERHUB_USERNAME/goggles-main:latest
                  RAILS_ENV=staging bundle exec rails assets:precompile
                  docker build -t $DOCKERHUB_USERNAME/goggles-main:latest --cache-from=$DOCKERHUB_USERNAME/goggles-main:latest -f Dockerfile.staging .
                  docker push $DOCKERHUB_USERNAME/goggles-main:latest


  deploy:
    <<: *common-config
    steps:
      - run:
          name: Setup deploy server login
          command: |
            mkdir -p .ssh
            ssh-keyscan -H $SSH_SERVER >> ~/.ssh/known_hosts
            echo Host $SSH_SERVER >> .ssh/config
            echo 'IdentityFile ~/.ssh/id_rsa_deploy' >> .ssh/config
            echo $id_rsa >> ~/.ssh/id_rsa_deploy
            echo $id_rsa_pub >> ~/.ssh/id_rsa_deploy.pub
            chmod 600 ~/.ssh/id_rsa_deploy
            chmod 644 ~/.ssh/id_rsa_deploy.pub
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Production DEPLOY
                command: |
                  echo "Git Tag << pipeline.git.tag >>"
                  ssh deploy@$SSH_SERVER "TAG=<< pipeline.git.tag >> MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD bash -c ./deploy_prod.sh"
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Staging DEPLOY
                command: |
                  ssh deploy@$SSH_SERVER "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD bash -c ./deploy_staging.sh"


workflows:
  full-build:
    jobs:
      - persisted-data
      - brakeman:
          requires:
            - persisted-data
      - rubocop:
          requires:
            - persisted-data
      - zeitwerk:
          requires:
            - persisted-data

      - rspec-components:
          requires:
            - brakeman
            - rubocop
            - zeitwerk
      - rspec-decorators:
          requires:
            - brakeman
            - rubocop
            - zeitwerk
      - rspec-requests:
          requires:
            - brakeman
            - rubocop
            - zeitwerk

      - rspec-helpers:
          requires:
            - rspec-components
            - rspec-decorators
      - rspec-mailers:
          requires:
            - rspec-components
            - rspec-decorators
      - rspec-views:
          requires:
            - rspec-components
            - rspec-decorators

      - rspec-jobs:
          requires:
            - rspec-helpers
      - rspec-strategies:
          requires:
            - rspec-mailers
      - rspec-integration:
          requires:
            - rspec-views

      - upload-coverage:
          requires:
            - rspec-requests
            - rspec-jobs
            - rspec-strategies
            - rspec-integration

      - cucumber-desktop:
          requires:
            - rspec-requests
      - cucumber-narrow:
          requires:
            - rspec-requests
      - cucumber-tablet:
          requires:
            - rspec-requests

      - docker-build:
          requires:
            - cucumber-desktop
            - cucumber-narrow
            - cucumber-tablet

      - deploy:
          requires:
            - docker-build
